# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:19
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_background', models.CharField(max_length=500)),
                ('project_objectives', models.CharField(max_length=200)),
                ('project_description', models.CharField(max_length=500)),
                ('project_dataset', models.CharField(max_length=500)),
                ('project_resources', models.CharField(max_length=500)),
                ('project_mentors', models.CharField(max_length=200)),
                ('project_complexity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('project_valid', models.BooleanField(default=False)),
                ('project_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('previous_leader', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('exam_results', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_description', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='tag_dislike_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_dislike_1', to='matchingsystem.Tag'),
        ),
        migrations.AddField(
            model_name='student',
            name='tag_like_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_1', to='matchingsystem.Tag'),
        ),
        migrations.AddField(
            model_name='student',
            name='tag_like_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_2', to='matchingsystem.Tag'),
        ),
        migrations.AddField(
            model_name='student',
            name='tag_like_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_3', to='matchingsystem.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Tag'),
        ),
    ]
