# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_complexity', models.IntegerField(default=0)),
                ('project_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('previous_leader', models.IntegerField(default=0)),
                ('tag_dislike_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_dislike_1', to='matchingsystem.Tag')),
                ('tag_like_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_1', to='matchingsystem.Tag')),
                ('tag_like_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_2', to='matchingsystem.Tag')),
                ('tag_like_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_3', to='matchingsystem.Tag')),
            ],
        ),
    ]
