# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tag_like_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_1', to='matchingsystem.Tag'),
        ),
    ]
