# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
