# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0002_auto_20180304_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tag_dislike_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_dislike_1', to='matchingsystem.Tag'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag_like_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_2', to='matchingsystem.Tag'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag_like_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_like_3', to='matchingsystem.Tag'),
        ),
    ]
