# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 16:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0003_auto_20180225_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='previous_leader',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
