# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0003_auto_20180304_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(to='matchingsystem.Module'),
        ),
    ]
