# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0004_auto_20180226_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
