# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0004_auto_20180310_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([]),
        ),
    ]
