# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 17:06
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0006_auto_20180301_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_results',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='project_module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Module'),
            preserve_default=False,
        ),
    ]
