# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0007_auto_20180302_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingsystem.Student')),
            ],
        ),
    ]
