# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsystem', '0008_studentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModel',
            new_name='StudentModule',
        ),
    ]
